version: '3.8'

services:
  products.api:
    build:
      context: .
      dockerfile: Products/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
      #Nginx Service
  webserver:
     image: nginx:latest
     container_name: webserver
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.4